# Generated by Django 5.2.3 on 2025-06-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_practice_date_remove_practice_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
